### ISSUE TITLE
Allow lists of SparkModel objects

### ISSUE THREAD

**Issue by jbpdl22** [mitchelllisle/sparkdantic#15]
Nice project!  Looks like SparkModel doesn't currently allow lists of SparkModel objects but this seems like a common case (in trying this on one of my pydantic models I ran into this error right off the bat).

I have a small change for this but looks like I can't push to your repo and create a PR.  Let me know if you'd like it.  

Cheers!

**Comment by mitchelllisle** [comment]
Hey, thanks for commenting. I've only recently setup this project so more than happy to have people contribute. I'll set up the repo to allow PRs in the next week or so when I have some time.

**Comment by mitchelllisle** [comment]
@jbpdl22  I have check the settings and you should be able to contribute by creating a fork and then making your changes. If you haven't used forks before check out this link https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks

I'll write up a bit more on how to contribute and how the project is intended to be worked with but feel free to submit your feature as a PR from your fork.

**Comment by jbpdl22** [comment]
#21 Created.

**Comment by mitchelllisle** [comment]
Merged and released! Changes released as part of `0.3.0` https://pypi.org/project/sparkdantic/
