### ISSUE TITLE
Leading underscores

### ISSUE THREAD

**Issue by dinis-rodrigues** [mitchelllisle/sparkdantic#249]
Currently Pydantic does not allow leading underscores for fields.

They state we should use `Field(alias='_id')` (for _id field).

But at the moment if I do this with sparkdantic, this field is not generated with `model_spark_schema()`

Any thoughts on how to do this?

**Comment by mitchelllisle** [comment]
Hi @dinis-rodrigues ,
I haven't added support for looking at the `alias` for the field name. Will look at adding this as part of the next release
