### ISSUE TITLE
MapType and ArrayType

### ISSUE THREAD

**Issue by randomgeek78** [mitchelllisle/sparkdantic#257]
Thanks for sharing this wonderful library. 

I had a question regarding how `padantic` hints are interpreted to generate spark schema for dict and list. 

I would expect the following:
- for `a: dict[str, str]`, I would expect it to generate `MapType(StringType(), StringType(), False)`
- for `a: dict[str, str | None]`, I would expect it to generate `MapType(StringType(), StringType(), True)`
- for `a: list[str]`, I would expect `ArrayType(StringType(), False)`
- for `a: list[str | None]`, I would expect `ArrayType(StringType(), True)`

But this is not what we see. The nullable flag for the values are ignored. Any good reason for ignoring this? 

From reading the code, the fix to do the "right thing" is very simple:

```
            value_type, nullable_ = cls._type_to_spark(args[1], [])
            return MapType(key_type, value_type, nullable_), nullable
```

and 

```
            inner_type = args[0]
            if cls._is_spark_model_subclass(inner_type):
                array_type = inner_type.model_spark_schema()
                nullable_ = nullable
            else:
                # Check if it's an accepted Enum
                array_type, nullable_ = cls._type_to_spark(inner_type, [])
            return ArrayType(array_type, nullable_), nullable
```

What was the motivation behind ignoring it? Thanks!

**Comment by mitchelllisle** [comment]
Thanks for the bug report! It was just something I missed implementing when going back and doing inner type checks. Have implented this in the latest release [v0.20.3](https://github.com/mitchelllisle/sparkdantic/releases/tag/v0.20.3)
