### ISSUE TITLE
Model conversion from pydantic

### ISSUE THREAD

**Issue by Bain-OS** [mitchelllisle/sparkdantic#322]
Hi :)

i have some existing pydantic models in my codebase, I want to convert these to spark models automatically. eg like this

```python
from pydantic import BaseModel
from sparkdantic import SparkModel
from typing import List

class A(BaseModel):
    a: str
 
class B(BaseModel):
    b: List[A]
 
class NaiveSparkB(SparkModel):
    b: List[A]
 
NaiveSparkB.model_spark_schema() ## <-- fails here with following error

# suggested solution something like
SparkB = SparkModel.convert_pydantic(B)
```

Error 
```
TypeError: Type <class '__main__.A'> not recognized
```

I don't have the option to change A and B to `SparkModel`s

**Comment by dan1elt0m** [comment]
Created PR to add support for BaseModel subclasses: https://github.com/mitchelllisle/sparkdantic/pull/336

**Comment by mitchelllisle** [comment]
New version [v0.22.0](https://github.com/mitchelllisle/sparkdantic/releases/tag/v0.22.0) released that implements this.

Thanks again @dan1elt0m !
