### ISSUE TITLE
Feature request: Add Support for UUID Type

### ISSUE THREAD

**Issue by dan1elt0m** [mitchelllisle/sparkdantic#347]
It would be great if Sparkdantic could support the UUID type in Pydantic models. 

Why?

- Useful: Lots of applications use UUIDs. Having this support would save time and effort.
- Consistent: Pydantic supports UUIDs, so Sparkdantic should too.
- In Demand: Many users probably need this feature.

**Comment by dan1elt0m** [comment]
PR: https://github.com/mitchelllisle/sparkdantic/pull/348

**Comment by mitchelllisle** [comment]
Released as part of [v0.23.0](https://github.com/mitchelllisle/sparkdantic/releases/tag/v0.23.0)
